CREATE TABLE CUSTOMER(
	customer_id SERIAL PRIMARY KEY,
	fname VARCHAR(50) NOT NULL,
	lname VARCHAR(50) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO CUSTOMER(fname,lname)
VALUES('Sarthak', 'Pandit');

INSERT INTO CUSTOMER(fname,lname)
VALUES('Karan', 'Negi'),
('Kunal', 'Nishad');

SELECT * FROM CUSTOMER;

-- CROSS Join
SELECT * FROM CUSTOMER CROSS JOIN EMPLOYEE;


-- INNER Join
SELECT * FROM EMPLOYEE
INNER JOIN CUSTOMER
ON EMPLOYEE.fname = CUSTOMER.fname

-- LEFT Join
SELECT * FROM EMPLOYEE
LEFT JOIN CUSTOMER
ON EMPLOYEE.fname = CUSTOMER.fname;

-- RIGHT Join
SELECT * FROM EMPLOYEE
RIGHT JOIN CUSTOMER
ON EMPLOYEE.fname = CUSTOMER.fname;