SELECT * FROM EMPLOYEE
WHERE fname LIKE 'A%';

SELECT * FROM EMPLOYEE
WHERE fname LIKE '%a';

SELECT * FROM EMPLOYEE
WHERE fname LIKE '%rt%';

SELECT * FROM EMPLOYEE
WHERE fname LIKE '____';

SELECT * FROM EMPLOYEE
WHERE fname LIKE '_a%';


