SELECT CONCAT(fname, lname) AS full_name
FROM EMPLOYEE;

SELECT CONCAT_WS(' ',fname, lname) AS full_name
FROM EMPLOYEE;

SELECT SUBSTRING(fname, 1,4) as sub_string
FROM EMPLOYEE;

SELECT REPLACE(dept, 'IT', 'TECH') FROM EMPLOYEE;

SELECT REVERSE(fname) FROM EMPLOYEE;

SELECT LENGTH(fname) FROM EMPLOYEE;

SELECT TRIM(fname) FROM EMPLOYEE;

SELECT RIGHT(fname,3) FROM EMPLOYEE;

SELECT LEFT(fname,3) FROM EMPLOYEE;

SELECT POSITION('ar' IN fname) FROM EMPLOYEE;

 