ALTER TABLE PATIENTS
ADD COLUMN country VARCHAR(50);

SELECT * FROM PATIENTS;

ALTER TABLE PATIENTS
RENAME COLUMN country TO citizenship;

SELECT * FROM PATIENTS;

ALTER TABLE PATIENTS
DROP COLUMN citizenship;

SELECT * FROM PATIENTS;