SELECT CONCAT_WS(' ',PATIENTS.fname, PATIENTS.lname) AS patient_fullname,
CONCAT_WS(' ',DOCTORS.fname, DOCTORS.lname) AS doctor_fullname
FROM APPOINTMENTS
JOIN DOCTORS
ON APPOINTMENTS.doctor_id = DOCTORS.doctor_id
JOIN PATIENTS
ON APPOINTMENTS.patient_id = PATIENTS.patient_id;

SELECT PATIENTS.fname, APPOINTMENTS.patient_id FROM PATIENTS
LEFT JOIN APPOINTMENTS
ON PATIENTS.patient_id = APPOINTMENTS.patient_id
WHERE APPOINTMENTS.patient_id IS NULL;